include(../../plugins/projectexplorer/projectexplorer.pri)
include(../../plugins/coreplugin/coreplugin.pri)
include(../../plugins/cpptools/cpptools.pri)
include(../../libs/utils/utils.pri)
include(../../libs/qmljs/qmljs.pri)
